"""initial_schema_22_tables

Revision ID: 4b4af00a227a
Revises: 
Create Date: 2026-09-25 12:31:04.537752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4af00a227a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_github')
    op.drop_table('user_assessments')
    op.drop_table('user_resumes')
    op.drop_table('user_roadmaps')
    op.drop_table('user_consent')
    op.alter_column('user_skills', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('user_skills', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('user_skills', 'skill_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('user_skills', 'self_level',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('user_skills', 'evidence_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('user_skills', 'final_level',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('user_skills', 'confidence',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('user_skills', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_user_skills_skill_name'), 'user_skills', ['skill_name'], unique=False)
    op.create_unique_constraint('uq_user_skill', 'user_skills', ['user_id', 'skill_name'])
    op.drop_column('user_skills', 'evidence_json')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('users', 'is_active')
    op.add_column('user_skills', sa.Column('evidence_json', sa.TEXT(), nullable=False))
    op.drop_constraint('uq_user_skill', 'user_skills', type_='unique')
    op.drop_index(op.f('ix_user_skills_skill_name'), table_name='user_skills')
    op.alter_column('user_skills', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('user_skills', 'confidence',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('user_skills', 'final_level',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('user_skills', 'evidence_status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('user_skills', 'self_level',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_skills', 'skill_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_skills', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_skills', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
    op.create_table('user_consent',
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('terms_accepted', sa.INTEGER(), nullable=False),
    sa.Column('consented_at', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_roadmaps',
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('target_role', sa.TEXT(), nullable=False),
    sa.Column('roadmap_nodes_json', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_resumes',
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('filename', sa.TEXT(), nullable=True),
    sa.Column('extracted_data_json', sa.TEXT(), nullable=False),
    sa.Column('uploaded_at', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_assessments',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('skill_name', sa.TEXT(), nullable=False),
    sa.Column('question_id', sa.TEXT(), nullable=False),
    sa.Column('question_type', sa.TEXT(), nullable=False),
    sa.Column('student_answer', sa.TEXT(), nullable=False),
    sa.Column('is_correct', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_github',
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('github_handle', sa.TEXT(), nullable=False),
    sa.Column('selected_repos_json', sa.TEXT(), nullable=False),
    sa.Column('evidence_summary_json', sa.TEXT(), nullable=True),
    sa.Column('analyzed_at', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###
